/*
 * SPDX-FileCopyrightText: 2026 IObundle, Lda
 *
 * SPDX-License-Identifier: MIT
 *
 * Py2HWSW Version 0.81 has generated this code (https://github.com/IObundle/py2hwsw).
 */

#ifndef H_IOB_AXISTREAM_IN_CSRS_CSRS_H
#define H_IOB_AXISTREAM_IN_CSRS_CSRS_H

/** @file iob_axistream_in_csrs.h
 *  @brief Function prototypes for the iob_axistream_in core.
 *
 *  This file contains the function prototypes to access the Control and Status
 * Registers (CSRs) for the iob_axistream_in core.
 *
 *  This file is automatically generated by Py2HWSW
 */

#include <stdint.h>

#include "iob_axistream_in_csrs_conf.h"

// Base Address
/**
 * @brief Set core base address.
 *
 * This function sets the base address for the core in the system. All other
 * accesses are offset from this base address.
 *
 * @param addr Base address for core.
 */
void iob_axistream_in_csrs_init_baseaddr(uint32_t addr);

// IO read and write function prototypes
/**
 * @brief Write access function prototype.
 *
 * @param addr Address to write to.
 * @param data_w Data width in bits.
 * @param value Value to write.
 */
void iob_write(uint32_t addr, uint32_t data_w, uint32_t value);
/**
 * @brief Read access function prototype.
 *
 * @param addr Address to write to.
 * @param data_w Data width in bits.
 * @return uint32_t Read data value.
 */
uint32_t iob_read(uint32_t addr, uint32_t data_w);

// Core Setters and Getters
/**
 * @brief Set soft_reset value.
 * Soft reset.
 * @param value soft_reset Value.
 */
void iob_axistream_in_csrs_set_soft_reset(uint8_t value);
/**
 * @brief Set enable value.
 * Enable peripheral.
 * @param value enable Value.
 */
void iob_axistream_in_csrs_set_enable(uint8_t value);
/**
 * @brief Get data value.
 * Data output.
 * @return uint32_t data value.
 */
uint32_t iob_axistream_in_csrs_get_data();
/**
 * @brief Set mode value.
 * Sets the operation mode: (0) data is read using CSR; (1) data is read using
 * system axistream interface.
 * @param value mode Value.
 */
void iob_axistream_in_csrs_set_mode(uint8_t value);
/**
 * @brief Get nwords value.
 * Read the number of words (with TDATA_W bits) written to the FIFO.
 * @return uint32_t nwords value.
 */
uint32_t iob_axistream_in_csrs_get_nwords();
/**
 * @brief Get tlast_detected value.
 * Read the TLAST detected status.
 * @return uint8_t tlast_detected value.
 */
uint8_t iob_axistream_in_csrs_get_tlast_detected();
/**
 * @brief Get fifo_full value.
 * Full (1), or non-full (0).
 * @return uint8_t fifo_full value.
 */
uint8_t iob_axistream_in_csrs_get_fifo_full();
/**
 * @brief Get fifo_empty value.
 * Full (1), or non-full (0).
 * @return uint8_t fifo_empty value.
 */
uint8_t iob_axistream_in_csrs_get_fifo_empty();
/**
 * @brief Set fifo_threshold value.
 * FIFO threshold level for interrupt signal
 * @param value fifo_threshold Value.
 */
void iob_axistream_in_csrs_set_fifo_threshold(uint32_t value);
/**
 * @brief Get fifo_level value.
 * Current FIFO level
 * @return uint32_t fifo_level value.
 */
uint32_t iob_axistream_in_csrs_get_fifo_level();
/**
 * @brief Get version value.
 * Product version. This 16-bit register uses nibbles to represent decimal
 * numbers using their binary values. The two most significant nibbles represent
 * the integral part of the version, and the two least significant nibbles
 * represent the decimal part. For example V12.34 is represented by 0x1234.
 * @return uint16_t version value.
 */
uint16_t iob_axistream_in_csrs_get_version();

#endif // H_IOB_AXISTREAM_IN_CSRS__CSRS_H
