/*
 * SPDX-FileCopyrightText: 2026 IObundle, Lda
 *
 * SPDX-License-Identifier: MIT
 *
 * Py2HWSW Version 0.81 has generated this code (https://github.com/IObundle/py2hwsw).
 */

#ifndef H_IOB_DMA_CSRS_CSRS_H
#define H_IOB_DMA_CSRS_CSRS_H

/** @file iob_dma_csrs.h
 *  @brief Function prototypes for the iob_dma core.
 *
 *  This file contains the function prototypes to access the Control and Status
 * Registers (CSRs) for the iob_dma core.
 *
 *  This file is automatically generated by Py2HWSW
 */

#include <stdint.h>

#include "iob_dma_csrs_conf.h"

// Base Address
/**
 * @brief Set core base address.
 *
 * This function sets the base address for the core in the system. All other
 * accesses are offset from this base address.
 *
 * @param addr Base address for core.
 */
void iob_dma_csrs_init_baseaddr(uint32_t addr);

// IO read and write function prototypes
/**
 * @brief Write access function prototype.
 *
 * @param addr Address to write to.
 * @param data_w Data width in bits.
 * @param value Value to write.
 */
void iob_write(uint32_t addr, uint32_t data_w, uint32_t value);
/**
 * @brief Read access function prototype.
 *
 * @param addr Address to write to.
 * @param data_w Data width in bits.
 * @return uint32_t Read data value.
 */
uint32_t iob_read(uint32_t addr, uint32_t data_w);

// Core Setters and Getters
/**
 * @brief Set w_addr value.
 * DMA write start address.
 * @param value w_addr Value.
 */
void iob_dma_csrs_set_w_addr(uint32_t value);
/**
 * @brief Set w_length value.
 * DMA write length in words.
 * @param value w_length Value.
 */
void iob_dma_csrs_set_w_length(uint32_t value);
/**
 * @brief Get w_busy value.
 * DMA write busy: high when the DMA controller is writing data.
 * @return uint8_t w_busy value.
 */
uint8_t iob_dma_csrs_get_w_busy();
/**
 * @brief Set w_start value.
 * DMA write start: writing any value to this register starts the DMA write
 * operation.
 * @param value w_start Value.
 */
void iob_dma_csrs_set_w_start(uint8_t value);
/**
 * @brief Set w_burstlen value.
 * AXI burst length for DMA write operations.
 * @param value w_burstlen Value.
 */
void iob_dma_csrs_set_w_burstlen(uint16_t value);
/**
 * @brief Get w_buf_level value.
 * Number of words left in the DMA write memory buffer to be transmitted.
 * @return uint32_t w_buf_level value.
 */
uint32_t iob_dma_csrs_get_w_buf_level();
/**
 * @brief Set r_addr value.
 * DMA read start address.
 * @param value r_addr Value.
 */
void iob_dma_csrs_set_r_addr(uint32_t value);
/**
 * @brief Set r_length value.
 * DMA read length in words.
 * @param value r_length Value.
 */
void iob_dma_csrs_set_r_length(uint32_t value);
/**
 * @brief Set r_start value.
 * DMA read start: writing any value to this register starts the DMA read
 * operation.
 * @param value r_start Value.
 */
void iob_dma_csrs_set_r_start(uint8_t value);
/**
 * @brief Get r_busy value.
 * DMA read busy: high when the DMA controller is reading data.
 * @return uint8_t r_busy value.
 */
uint8_t iob_dma_csrs_get_r_busy();
/**
 * @brief Set r_burstlen value.
 * AXI burst length for DMA read operations.
 * @param value r_burstlen Value.
 */
void iob_dma_csrs_set_r_burstlen(uint16_t value);
/**
 * @brief Get r_buf_level value.
 * Number of words left in the DMA read memory buffer to be received.
 * @return uint32_t r_buf_level value.
 */
uint32_t iob_dma_csrs_get_r_buf_level();
/**
 * @brief Get version value.
 * Product version. This 16-bit register uses nibbles to represent decimal
 * numbers using their binary values. The two most significant nibbles represent
 * the integral part of the version, and the two least significant nibbles
 * represent the decimal part. For example V12.34 is represented by 0x1234.
 * @return uint16_t version value.
 */
uint16_t iob_dma_csrs_get_version();

#endif // H_IOB_DMA_CSRS__CSRS_H
