/*
 * SPDX-FileCopyrightText: 2026 IObundle, Lda
 *
 * SPDX-License-Identifier: MIT
 *
 * Py2HWSW Version 0.81 has generated this code (https://github.com/IObundle/py2hwsw).
 */

#ifndef H_IOB_AXI_INTERCONNECT_CONF_H
#define H_IOB_AXI_INTERCONNECT_CONF_H

#define IOB_AXI_INTERCONNECT_ID_WIDTH 8
#define IOB_AXI_INTERCONNECT_DATA_WIDTH 32
#define IOB_AXI_INTERCONNECT_ADDR_WIDTH 32
#define IOB_AXI_INTERCONNECT_M_ADDR_WIDTH 32
#define IOB_AXI_INTERCONNECT_S_COUNT 4
#define IOB_AXI_INTERCONNECT_M_COUNT 4
#define IOB_AXI_INTERCONNECT_VERSION 0x0081

#endif // H_IOB_AXI_INTERCONNECT_CONF_H
