/*
 * SPDX-FileCopyrightText: 2026 IObundle, Lda
 *
 * SPDX-License-Identifier: MIT
 *
 * Py2HWSW Version 0.81 has generated this code (https://github.com/IObundle/py2hwsw).
 */

#ifndef H_IOB_AXISTREAM_IN_CSRS_CONF_H
#define H_IOB_AXISTREAM_IN_CSRS_CONF_H

#define IOB_AXISTREAM_IN_CSRS_ADDR_W 5
#define IOB_AXISTREAM_IN_CSRS_DATA_W 32
#define IOB_AXISTREAM_IN_CSRS_TDATA_W 8
#define IOB_AXISTREAM_IN_CSRS_FIFO_ADDR_W 4
#define IOB_AXISTREAM_IN_CSRS_SOFT_RESET_ADDR 0
#define IOB_AXISTREAM_IN_CSRS_SOFT_RESET_W 8
#define IOB_AXISTREAM_IN_CSRS_ENABLE_ADDR 1
#define IOB_AXISTREAM_IN_CSRS_ENABLE_W 8
#define IOB_AXISTREAM_IN_CSRS_DATA_ADDR 4
#define IOB_AXISTREAM_IN_CSRS_DATA_W 32
#define IOB_AXISTREAM_IN_CSRS_MODE_ADDR 8
#define IOB_AXISTREAM_IN_CSRS_MODE_W 8
#define IOB_AXISTREAM_IN_CSRS_NWORDS_ADDR 12
#define IOB_AXISTREAM_IN_CSRS_NWORDS_W 32
#define IOB_AXISTREAM_IN_CSRS_TLAST_DETECTED_ADDR 16
#define IOB_AXISTREAM_IN_CSRS_TLAST_DETECTED_W 8
#define IOB_AXISTREAM_IN_CSRS_FIFO_FULL_ADDR 17
#define IOB_AXISTREAM_IN_CSRS_FIFO_FULL_W 8
#define IOB_AXISTREAM_IN_CSRS_FIFO_EMPTY_ADDR 18
#define IOB_AXISTREAM_IN_CSRS_FIFO_EMPTY_W 8
#define IOB_AXISTREAM_IN_CSRS_FIFO_THRESHOLD_ADDR 20
#define IOB_AXISTREAM_IN_CSRS_FIFO_THRESHOLD_W 32
#define IOB_AXISTREAM_IN_CSRS_FIFO_LEVEL_ADDR 24
#define IOB_AXISTREAM_IN_CSRS_FIFO_LEVEL_W 32
#define IOB_AXISTREAM_IN_CSRS_VERSION_ADDR 28
#define IOB_AXISTREAM_IN_CSRS_VERSION_W 16
#define IOB_AXISTREAM_IN_CSRS_VERSION 0x0081

#endif // H_IOB_AXISTREAM_IN_CSRS_CONF_H
