/*
 * SPDX-FileCopyrightText: 2026 IObundle, Lda
 *
 * SPDX-License-Identifier: MIT
 *
 * Py2HWSW Version 0.81 has generated this code (https://github.com/IObundle/py2hwsw).
 */

#ifndef H_IOB_ETH_CSRS_CSRS_H
#define H_IOB_ETH_CSRS_CSRS_H

/** @file iob_eth_csrs.h
 *  @brief Function prototypes for the iob_eth core.
 *
 *  This file contains the function prototypes to access the Control and Status
 * Registers (CSRs) for the iob_eth core.
 *
 *  This file is automatically generated by Py2HWSW
 */

#include <stdint.h>

#include "iob_eth_csrs_conf.h"

// Base Address
/**
 * @brief Set core base address.
 *
 * This function sets the base address for the core in the system. All other
 * accesses are offset from this base address.
 *
 * @param addr Base address for core.
 */
void iob_eth_csrs_init_baseaddr(uint32_t addr);

// IO read and write function prototypes
/**
 * @brief Write access function prototype.
 *
 * @param addr Address to write to.
 * @param data_w Data width in bits.
 * @param value Value to write.
 */
void iob_write(uint32_t addr, uint32_t data_w, uint32_t value);
/**
 * @brief Read access function prototype.
 *
 * @param addr Address to write to.
 * @param data_w Data width in bits.
 * @return uint32_t Read data value.
 */
uint32_t iob_read(uint32_t addr, uint32_t data_w);

// Core Setters and Getters
/**
 * @brief Set moder value.
 * Mode Register
 * @param value moder Value.
 */
void iob_eth_csrs_set_moder(uint32_t value);
/**
 * @brief Get moder value.
 * Mode Register
 * @return uint32_t moder value.
 */
uint32_t iob_eth_csrs_get_moder();
/**
 * @brief Set int_source value.
 * Interrupt Source Register
 * @param value int_source Value.
 */
void iob_eth_csrs_set_int_source(uint32_t value);
/**
 * @brief Get int_source value.
 * Interrupt Source Register
 * @return uint32_t int_source value.
 */
uint32_t iob_eth_csrs_get_int_source();
/**
 * @brief Set int_mask value.
 * Interrupt Mask Register
 * @param value int_mask Value.
 */
void iob_eth_csrs_set_int_mask(uint32_t value);
/**
 * @brief Get int_mask value.
 * Interrupt Mask Register
 * @return uint32_t int_mask value.
 */
uint32_t iob_eth_csrs_get_int_mask();
/**
 * @brief Set ipgt value.
 * Back to Back Inter Packet Gap Register
 * @param value ipgt Value.
 */
void iob_eth_csrs_set_ipgt(uint32_t value);
/**
 * @brief Get ipgt value.
 * Back to Back Inter Packet Gap Register
 * @return uint32_t ipgt value.
 */
uint32_t iob_eth_csrs_get_ipgt();
/**
 * @brief Set ipgr1 value.
 * Non Back to Back Inter Packet Gap Register 1
 * @param value ipgr1 Value.
 */
void iob_eth_csrs_set_ipgr1(uint32_t value);
/**
 * @brief Get ipgr1 value.
 * Non Back to Back Inter Packet Gap Register 1
 * @return uint32_t ipgr1 value.
 */
uint32_t iob_eth_csrs_get_ipgr1();
/**
 * @brief Set ipgr2 value.
 * Non Back to Back Inter Packet Gap Register 2
 * @param value ipgr2 Value.
 */
void iob_eth_csrs_set_ipgr2(uint32_t value);
/**
 * @brief Get ipgr2 value.
 * Non Back to Back Inter Packet Gap Register 2
 * @return uint32_t ipgr2 value.
 */
uint32_t iob_eth_csrs_get_ipgr2();
/**
 * @brief Set packetlen value.
 * Packet Length (minimum and maximum) Register
 * @param value packetlen Value.
 */
void iob_eth_csrs_set_packetlen(uint32_t value);
/**
 * @brief Get packetlen value.
 * Packet Length (minimum and maximum) Register
 * @return uint32_t packetlen value.
 */
uint32_t iob_eth_csrs_get_packetlen();
/**
 * @brief Set collconf value.
 * Collision and Retry Configuration
 * @param value collconf Value.
 */
void iob_eth_csrs_set_collconf(uint32_t value);
/**
 * @brief Get collconf value.
 * Collision and Retry Configuration
 * @return uint32_t collconf value.
 */
uint32_t iob_eth_csrs_get_collconf();
/**
 * @brief Set tx_bd_num value.
 * Transmit Buffer Descriptor Number
 * @param value tx_bd_num Value.
 */
void iob_eth_csrs_set_tx_bd_num(uint32_t value);
/**
 * @brief Get tx_bd_num value.
 * Transmit Buffer Descriptor Number
 * @return uint32_t tx_bd_num value.
 */
uint32_t iob_eth_csrs_get_tx_bd_num();
/**
 * @brief Set ctrlmoder value.
 * Control Module Mode Register
 * @param value ctrlmoder Value.
 */
void iob_eth_csrs_set_ctrlmoder(uint32_t value);
/**
 * @brief Get ctrlmoder value.
 * Control Module Mode Register
 * @return uint32_t ctrlmoder value.
 */
uint32_t iob_eth_csrs_get_ctrlmoder();
/**
 * @brief Set miimoder value.
 * MII Mode Register
 * @param value miimoder Value.
 */
void iob_eth_csrs_set_miimoder(uint32_t value);
/**
 * @brief Get miimoder value.
 * MII Mode Register
 * @return uint32_t miimoder value.
 */
uint32_t iob_eth_csrs_get_miimoder();
/**
 * @brief Set miicommand value.
 * MII Command Register
 * @param value miicommand Value.
 */
void iob_eth_csrs_set_miicommand(uint32_t value);
/**
 * @brief Get miicommand value.
 * MII Command Register
 * @return uint32_t miicommand value.
 */
uint32_t iob_eth_csrs_get_miicommand();
/**
 * @brief Set miiaddress value.
 * MII Address Register. Contains the PHY address and the register within the
 * PHY address
 * @param value miiaddress Value.
 */
void iob_eth_csrs_set_miiaddress(uint32_t value);
/**
 * @brief Get miiaddress value.
 * MII Address Register. Contains the PHY address and the register within the
 * PHY address
 * @return uint32_t miiaddress value.
 */
uint32_t iob_eth_csrs_get_miiaddress();
/**
 * @brief Set miitx_data value.
 * MII Transmit Data. The data to be transmitted to the PHY
 * @param value miitx_data Value.
 */
void iob_eth_csrs_set_miitx_data(uint32_t value);
/**
 * @brief Get miitx_data value.
 * MII Transmit Data. The data to be transmitted to the PHY
 * @return uint32_t miitx_data value.
 */
uint32_t iob_eth_csrs_get_miitx_data();
/**
 * @brief Set miirx_data value.
 * MII Receive Data. The data received from the PHY
 * @param value miirx_data Value.
 */
void iob_eth_csrs_set_miirx_data(uint32_t value);
/**
 * @brief Get miirx_data value.
 * MII Receive Data. The data received from the PHY
 * @return uint32_t miirx_data value.
 */
uint32_t iob_eth_csrs_get_miirx_data();
/**
 * @brief Set miistatus value.
 * MII Status Register
 * @param value miistatus Value.
 */
void iob_eth_csrs_set_miistatus(uint32_t value);
/**
 * @brief Get miistatus value.
 * MII Status Register
 * @return uint32_t miistatus value.
 */
uint32_t iob_eth_csrs_get_miistatus();
/**
 * @brief Set mac_addr0 value.
 * MAC Individual Address0. The LSB four bytes of the individual address are
 * written to this register
 * @param value mac_addr0 Value.
 */
void iob_eth_csrs_set_mac_addr0(uint32_t value);
/**
 * @brief Get mac_addr0 value.
 * MAC Individual Address0. The LSB four bytes of the individual address are
 * written to this register
 * @return uint32_t mac_addr0 value.
 */
uint32_t iob_eth_csrs_get_mac_addr0();
/**
 * @brief Set mac_addr1 value.
 * MAC Individual Address1. The MSB two bytes of the individual address are
 * written to this register
 * @param value mac_addr1 Value.
 */
void iob_eth_csrs_set_mac_addr1(uint32_t value);
/**
 * @brief Get mac_addr1 value.
 * MAC Individual Address1. The MSB two bytes of the individual address are
 * written to this register
 * @return uint32_t mac_addr1 value.
 */
uint32_t iob_eth_csrs_get_mac_addr1();
/**
 * @brief Set eth_hash0_adr value.
 * HASH0 Register
 * @param value eth_hash0_adr Value.
 */
void iob_eth_csrs_set_eth_hash0_adr(uint32_t value);
/**
 * @brief Get eth_hash0_adr value.
 * HASH0 Register
 * @return uint32_t eth_hash0_adr value.
 */
uint32_t iob_eth_csrs_get_eth_hash0_adr();
/**
 * @brief Set eth_hash1_adr value.
 * HASH1 Register
 * @param value eth_hash1_adr Value.
 */
void iob_eth_csrs_set_eth_hash1_adr(uint32_t value);
/**
 * @brief Get eth_hash1_adr value.
 * HASH1 Register
 * @return uint32_t eth_hash1_adr value.
 */
uint32_t iob_eth_csrs_get_eth_hash1_adr();
/**
 * @brief Set eth_txctrl value.
 * Transmit Control Register
 * @param value eth_txctrl Value.
 */
void iob_eth_csrs_set_eth_txctrl(uint32_t value);
/**
 * @brief Get eth_txctrl value.
 * Transmit Control Register
 * @return uint32_t eth_txctrl value.
 */
uint32_t iob_eth_csrs_get_eth_txctrl();
/**
 * @brief Get tx_bd_cnt value.
 * Buffer descriptor number of current TX frame
 * @return uint8_t tx_bd_cnt value.
 */
uint8_t iob_eth_csrs_get_tx_bd_cnt();
/**
 * @brief Get rx_bd_cnt value.
 * Buffer descriptor number of current RX frame
 * @return uint8_t rx_bd_cnt value.
 */
uint8_t iob_eth_csrs_get_rx_bd_cnt();
/**
 * @brief Get tx_word_cnt value.
 * Word number of current TX frame
 * @return uint32_t tx_word_cnt value.
 */
uint32_t iob_eth_csrs_get_tx_word_cnt();
/**
 * @brief Get rx_word_cnt value.
 * Word number of current RX frame
 * @return uint32_t rx_word_cnt value.
 */
uint32_t iob_eth_csrs_get_rx_word_cnt();
/**
 * @brief Get rx_nbytes value.
 * Size of received frame in bytes. Will be zero if no frame has been received.
 * Will reset to zero when cpu completes reading the frame.
 * @return uint32_t rx_nbytes value.
 */
uint32_t iob_eth_csrs_get_rx_nbytes();
/**
 * @brief Set frame_word value.
 * Frame word to transfer to/from buffer
 * @param value frame_word Value.
 */
void iob_eth_csrs_set_frame_word(uint8_t value);
/**
 * @brief Get frame_word value.
 * Frame word to transfer to/from buffer
 * @return uint8_t frame_word value.
 */
uint8_t iob_eth_csrs_get_frame_word();
/**
 * @brief Get phy_rst_val value.
 * Current PHY reset signal value
 * @return uint8_t phy_rst_val value.
 */
uint8_t iob_eth_csrs_get_phy_rst_val();
/**
 * @brief Set bd value.
 * Buffer descriptors
 * @param value bd Value.
 * @param addr bd array address.
 */
void iob_eth_csrs_set_bd(uint32_t value, int addr);
/**
 * @brief Get bd value.
 * Buffer descriptors
 * @param addr bd array address.
 * @return uint32_t bd value.
 */
uint32_t iob_eth_csrs_get_bd(int addr);
/**
 * @brief Get version value.
 * Product version. This 16-bit register uses nibbles to represent decimal
 * numbers using their binary values. The two most significant nibbles represent
 * the integral part of the version, and the two least significant nibbles
 * represent the decimal part. For example V12.34 is represented by 0x1234.
 * @return uint16_t version value.
 */
uint16_t iob_eth_csrs_get_version();

#endif // H_IOB_ETH_CSRS__CSRS_H
