/* This file was automatically generated by:
 * `create_driver_header_file_list` method of
 * `create_peripheral_device_drivers.py`
 */

#ifndef H_IOB_ETH_DRIVER_FILES_H
#define H_IOB_ETH_DRIVER_FILES_H

/** @file
 *  @brief iob_eth driver file paths.
 */

#define IOB_ETH_DRIVER_NAME "iob_eth"      /**< Driver name. */
#define IOB_ETH_DRIVER_CLASS "iob_eth"     /**< Driver class. */
#define IOB_ETH_DEVICE_FILE "/dev/iob_eth" /**< Device file path. */
#define IOB_ETH_DEVICE_CLASS                                                   \
  "/sys/class/" IOB_ETH_DRIVER_CLASS                                           \
  "/" IOB_ETH_DRIVER_NAME /**< Device class path. */

/**
 * @brief System file paths for CSRs.
 */
#define IOB_ETH_SYSFILE_MODER                                                  \
  IOB_ETH_DEVICE_CLASS "/moder" /**< System file path for moder CSR. */
#define IOB_ETH_SYSFILE_INT_SOURCE                                             \
  IOB_ETH_DEVICE_CLASS                                                         \
      "/int_source" /**< System file path for int_source CSR. */
#define IOB_ETH_SYSFILE_INT_MASK                                               \
  IOB_ETH_DEVICE_CLASS "/int_mask" /**< System file path for int_mask CSR. */
#define IOB_ETH_SYSFILE_IPGT                                                   \
  IOB_ETH_DEVICE_CLASS "/ipgt" /**< System file path for ipgt CSR. */
#define IOB_ETH_SYSFILE_IPGR1                                                  \
  IOB_ETH_DEVICE_CLASS "/ipgr1" /**< System file path for ipgr1 CSR. */
#define IOB_ETH_SYSFILE_IPGR2                                                  \
  IOB_ETH_DEVICE_CLASS "/ipgr2" /**< System file path for ipgr2 CSR. */
#define IOB_ETH_SYSFILE_PACKETLEN                                              \
  IOB_ETH_DEVICE_CLASS "/packetlen" /**< System file path for packetlen CSR.   \
                                     */
#define IOB_ETH_SYSFILE_COLLCONF                                               \
  IOB_ETH_DEVICE_CLASS "/collconf" /**< System file path for collconf CSR. */
#define IOB_ETH_SYSFILE_TX_BD_NUM                                              \
  IOB_ETH_DEVICE_CLASS "/tx_bd_num" /**< System file path for tx_bd_num CSR.   \
                                     */
#define IOB_ETH_SYSFILE_CTRLMODER                                              \
  IOB_ETH_DEVICE_CLASS "/ctrlmoder" /**< System file path for ctrlmoder CSR.   \
                                     */
#define IOB_ETH_SYSFILE_MIIMODER                                               \
  IOB_ETH_DEVICE_CLASS "/miimoder" /**< System file path for miimoder CSR. */
#define IOB_ETH_SYSFILE_MIICOMMAND                                             \
  IOB_ETH_DEVICE_CLASS                                                         \
      "/miicommand" /**< System file path for miicommand CSR. */
#define IOB_ETH_SYSFILE_MIIADDRESS                                             \
  IOB_ETH_DEVICE_CLASS                                                         \
      "/miiaddress" /**< System file path for miiaddress CSR. */
#define IOB_ETH_SYSFILE_MIITX_DATA                                             \
  IOB_ETH_DEVICE_CLASS                                                         \
      "/miitx_data" /**< System file path for miitx_data CSR. */
#define IOB_ETH_SYSFILE_MIIRX_DATA                                             \
  IOB_ETH_DEVICE_CLASS                                                         \
      "/miirx_data" /**< System file path for miirx_data CSR. */
#define IOB_ETH_SYSFILE_MIISTATUS                                              \
  IOB_ETH_DEVICE_CLASS "/miistatus" /**< System file path for miistatus CSR.   \
                                     */
#define IOB_ETH_SYSFILE_MAC_ADDR0                                              \
  IOB_ETH_DEVICE_CLASS "/mac_addr0" /**< System file path for mac_addr0 CSR.   \
                                     */
#define IOB_ETH_SYSFILE_MAC_ADDR1                                              \
  IOB_ETH_DEVICE_CLASS "/mac_addr1" /**< System file path for mac_addr1 CSR.   \
                                     */
#define IOB_ETH_SYSFILE_ETH_HASH0_ADR                                          \
  IOB_ETH_DEVICE_CLASS                                                         \
      "/eth_hash0_adr" /**< System file path for eth_hash0_adr CSR. */
#define IOB_ETH_SYSFILE_ETH_HASH1_ADR                                          \
  IOB_ETH_DEVICE_CLASS                                                         \
      "/eth_hash1_adr" /**< System file path for eth_hash1_adr CSR. */
#define IOB_ETH_SYSFILE_ETH_TXCTRL                                             \
  IOB_ETH_DEVICE_CLASS                                                         \
      "/eth_txctrl" /**< System file path for eth_txctrl CSR. */
#define IOB_ETH_SYSFILE_TX_BD_CNT                                              \
  IOB_ETH_DEVICE_CLASS "/tx_bd_cnt" /**< System file path for tx_bd_cnt CSR.   \
                                     */
#define IOB_ETH_SYSFILE_RX_BD_CNT                                              \
  IOB_ETH_DEVICE_CLASS "/rx_bd_cnt" /**< System file path for rx_bd_cnt CSR.   \
                                     */
#define IOB_ETH_SYSFILE_TX_WORD_CNT                                            \
  IOB_ETH_DEVICE_CLASS                                                         \
      "/tx_word_cnt" /**< System file path for tx_word_cnt CSR. */
#define IOB_ETH_SYSFILE_RX_WORD_CNT                                            \
  IOB_ETH_DEVICE_CLASS                                                         \
      "/rx_word_cnt" /**< System file path for rx_word_cnt CSR. */
#define IOB_ETH_SYSFILE_RX_NBYTES                                              \
  IOB_ETH_DEVICE_CLASS "/rx_nbytes" /**< System file path for rx_nbytes CSR.   \
                                     */
#define IOB_ETH_SYSFILE_FRAME_WORD                                             \
  IOB_ETH_DEVICE_CLASS                                                         \
      "/frame_word" /**< System file path for frame_word CSR. */
#define IOB_ETH_SYSFILE_PHY_RST_VAL                                            \
  IOB_ETH_DEVICE_CLASS                                                         \
      "/phy_rst_val" /**< System file path for phy_rst_val CSR. */
#define IOB_ETH_SYSFILE_BD                                                     \
  IOB_ETH_DEVICE_CLASS "/bd" /**< System file path for bd CSR. */
#define IOB_ETH_SYSFILE_VERSION                                                \
  IOB_ETH_DEVICE_CLASS "/version" /**< System file path for version CSR. */

#include "iob_eth_csrs_conf.h"

#endif // H_IOB_ETH_DRIVER_FILES_H
