/* This file was automatically generated by:
 * `create_sysfs_driver_header_file` method of
 * `create_peripheral_device_drivers.py`
 */

#ifndef H_IOB_ETH_SYSFS_H
#define H_IOB_ETH_SYSFS_H

// Sysfs show/store functions
static ssize_t sysfs_enosys_show(struct device *dev,
                                 struct device_attribute *attr, char *buf) {
  return -ENOSYS;
}

static ssize_t sysfs_enosys_store(struct device *dev,
                                  struct device_attribute *attr,
                                  const char *buf, size_t count) {
  return -ENOSYS;
}

static ssize_t sysfs_moder_store(struct device *dev,
                                 struct device_attribute *attr, const char *buf,
                                 size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_eth_mutex)) {
    pr_info("[iob_eth] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_eth_mutex);
    return ret;
  }
  iob_data_write_reg(iob_eth_data.regbase, value, IOB_ETH_CSRS_MODER_ADDR,
                     IOB_ETH_CSRS_MODER_W);
  mutex_unlock(&iob_eth_mutex);
  pr_info("[iob_eth] Sysfs - Write moder: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_int_source_store(struct device *dev,
                                      struct device_attribute *attr,
                                      const char *buf, size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_eth_mutex)) {
    pr_info("[iob_eth] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_eth_mutex);
    return ret;
  }
  iob_data_write_reg(iob_eth_data.regbase, value, IOB_ETH_CSRS_INT_SOURCE_ADDR,
                     IOB_ETH_CSRS_INT_SOURCE_W);
  mutex_unlock(&iob_eth_mutex);
  pr_info("[iob_eth] Sysfs - Write int_source: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_int_mask_store(struct device *dev,
                                    struct device_attribute *attr,
                                    const char *buf, size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_eth_mutex)) {
    pr_info("[iob_eth] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_eth_mutex);
    return ret;
  }
  iob_data_write_reg(iob_eth_data.regbase, value, IOB_ETH_CSRS_INT_MASK_ADDR,
                     IOB_ETH_CSRS_INT_MASK_W);
  mutex_unlock(&iob_eth_mutex);
  pr_info("[iob_eth] Sysfs - Write int_mask: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_ipgt_store(struct device *dev,
                                struct device_attribute *attr, const char *buf,
                                size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_eth_mutex)) {
    pr_info("[iob_eth] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_eth_mutex);
    return ret;
  }
  iob_data_write_reg(iob_eth_data.regbase, value, IOB_ETH_CSRS_IPGT_ADDR,
                     IOB_ETH_CSRS_IPGT_W);
  mutex_unlock(&iob_eth_mutex);
  pr_info("[iob_eth] Sysfs - Write ipgt: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_ipgr1_store(struct device *dev,
                                 struct device_attribute *attr, const char *buf,
                                 size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_eth_mutex)) {
    pr_info("[iob_eth] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_eth_mutex);
    return ret;
  }
  iob_data_write_reg(iob_eth_data.regbase, value, IOB_ETH_CSRS_IPGR1_ADDR,
                     IOB_ETH_CSRS_IPGR1_W);
  mutex_unlock(&iob_eth_mutex);
  pr_info("[iob_eth] Sysfs - Write ipgr1: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_ipgr2_store(struct device *dev,
                                 struct device_attribute *attr, const char *buf,
                                 size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_eth_mutex)) {
    pr_info("[iob_eth] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_eth_mutex);
    return ret;
  }
  iob_data_write_reg(iob_eth_data.regbase, value, IOB_ETH_CSRS_IPGR2_ADDR,
                     IOB_ETH_CSRS_IPGR2_W);
  mutex_unlock(&iob_eth_mutex);
  pr_info("[iob_eth] Sysfs - Write ipgr2: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_packetlen_store(struct device *dev,
                                     struct device_attribute *attr,
                                     const char *buf, size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_eth_mutex)) {
    pr_info("[iob_eth] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_eth_mutex);
    return ret;
  }
  iob_data_write_reg(iob_eth_data.regbase, value, IOB_ETH_CSRS_PACKETLEN_ADDR,
                     IOB_ETH_CSRS_PACKETLEN_W);
  mutex_unlock(&iob_eth_mutex);
  pr_info("[iob_eth] Sysfs - Write packetlen: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_collconf_store(struct device *dev,
                                    struct device_attribute *attr,
                                    const char *buf, size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_eth_mutex)) {
    pr_info("[iob_eth] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_eth_mutex);
    return ret;
  }
  iob_data_write_reg(iob_eth_data.regbase, value, IOB_ETH_CSRS_COLLCONF_ADDR,
                     IOB_ETH_CSRS_COLLCONF_W);
  mutex_unlock(&iob_eth_mutex);
  pr_info("[iob_eth] Sysfs - Write collconf: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_tx_bd_num_store(struct device *dev,
                                     struct device_attribute *attr,
                                     const char *buf, size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_eth_mutex)) {
    pr_info("[iob_eth] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_eth_mutex);
    return ret;
  }
  iob_data_write_reg(iob_eth_data.regbase, value, IOB_ETH_CSRS_TX_BD_NUM_ADDR,
                     IOB_ETH_CSRS_TX_BD_NUM_W);
  mutex_unlock(&iob_eth_mutex);
  pr_info("[iob_eth] Sysfs - Write tx_bd_num: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_ctrlmoder_store(struct device *dev,
                                     struct device_attribute *attr,
                                     const char *buf, size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_eth_mutex)) {
    pr_info("[iob_eth] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_eth_mutex);
    return ret;
  }
  iob_data_write_reg(iob_eth_data.regbase, value, IOB_ETH_CSRS_CTRLMODER_ADDR,
                     IOB_ETH_CSRS_CTRLMODER_W);
  mutex_unlock(&iob_eth_mutex);
  pr_info("[iob_eth] Sysfs - Write ctrlmoder: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_miimoder_store(struct device *dev,
                                    struct device_attribute *attr,
                                    const char *buf, size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_eth_mutex)) {
    pr_info("[iob_eth] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_eth_mutex);
    return ret;
  }
  iob_data_write_reg(iob_eth_data.regbase, value, IOB_ETH_CSRS_MIIMODER_ADDR,
                     IOB_ETH_CSRS_MIIMODER_W);
  mutex_unlock(&iob_eth_mutex);
  pr_info("[iob_eth] Sysfs - Write miimoder: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_miicommand_store(struct device *dev,
                                      struct device_attribute *attr,
                                      const char *buf, size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_eth_mutex)) {
    pr_info("[iob_eth] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_eth_mutex);
    return ret;
  }
  iob_data_write_reg(iob_eth_data.regbase, value, IOB_ETH_CSRS_MIICOMMAND_ADDR,
                     IOB_ETH_CSRS_MIICOMMAND_W);
  mutex_unlock(&iob_eth_mutex);
  pr_info("[iob_eth] Sysfs - Write miicommand: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_miiaddress_store(struct device *dev,
                                      struct device_attribute *attr,
                                      const char *buf, size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_eth_mutex)) {
    pr_info("[iob_eth] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_eth_mutex);
    return ret;
  }
  iob_data_write_reg(iob_eth_data.regbase, value, IOB_ETH_CSRS_MIIADDRESS_ADDR,
                     IOB_ETH_CSRS_MIIADDRESS_W);
  mutex_unlock(&iob_eth_mutex);
  pr_info("[iob_eth] Sysfs - Write miiaddress: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_miitx_data_store(struct device *dev,
                                      struct device_attribute *attr,
                                      const char *buf, size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_eth_mutex)) {
    pr_info("[iob_eth] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_eth_mutex);
    return ret;
  }
  iob_data_write_reg(iob_eth_data.regbase, value, IOB_ETH_CSRS_MIITX_DATA_ADDR,
                     IOB_ETH_CSRS_MIITX_DATA_W);
  mutex_unlock(&iob_eth_mutex);
  pr_info("[iob_eth] Sysfs - Write miitx_data: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_miirx_data_store(struct device *dev,
                                      struct device_attribute *attr,
                                      const char *buf, size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_eth_mutex)) {
    pr_info("[iob_eth] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_eth_mutex);
    return ret;
  }
  iob_data_write_reg(iob_eth_data.regbase, value, IOB_ETH_CSRS_MIIRX_DATA_ADDR,
                     IOB_ETH_CSRS_MIIRX_DATA_W);
  mutex_unlock(&iob_eth_mutex);
  pr_info("[iob_eth] Sysfs - Write miirx_data: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_miistatus_store(struct device *dev,
                                     struct device_attribute *attr,
                                     const char *buf, size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_eth_mutex)) {
    pr_info("[iob_eth] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_eth_mutex);
    return ret;
  }
  iob_data_write_reg(iob_eth_data.regbase, value, IOB_ETH_CSRS_MIISTATUS_ADDR,
                     IOB_ETH_CSRS_MIISTATUS_W);
  mutex_unlock(&iob_eth_mutex);
  pr_info("[iob_eth] Sysfs - Write miistatus: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_mac_addr0_store(struct device *dev,
                                     struct device_attribute *attr,
                                     const char *buf, size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_eth_mutex)) {
    pr_info("[iob_eth] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_eth_mutex);
    return ret;
  }
  iob_data_write_reg(iob_eth_data.regbase, value, IOB_ETH_CSRS_MAC_ADDR0_ADDR,
                     IOB_ETH_CSRS_MAC_ADDR0_W);
  mutex_unlock(&iob_eth_mutex);
  pr_info("[iob_eth] Sysfs - Write mac_addr0: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_mac_addr1_store(struct device *dev,
                                     struct device_attribute *attr,
                                     const char *buf, size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_eth_mutex)) {
    pr_info("[iob_eth] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_eth_mutex);
    return ret;
  }
  iob_data_write_reg(iob_eth_data.regbase, value, IOB_ETH_CSRS_MAC_ADDR1_ADDR,
                     IOB_ETH_CSRS_MAC_ADDR1_W);
  mutex_unlock(&iob_eth_mutex);
  pr_info("[iob_eth] Sysfs - Write mac_addr1: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_eth_hash0_adr_store(struct device *dev,
                                         struct device_attribute *attr,
                                         const char *buf, size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_eth_mutex)) {
    pr_info("[iob_eth] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_eth_mutex);
    return ret;
  }
  iob_data_write_reg(iob_eth_data.regbase, value,
                     IOB_ETH_CSRS_ETH_HASH0_ADR_ADDR,
                     IOB_ETH_CSRS_ETH_HASH0_ADR_W);
  mutex_unlock(&iob_eth_mutex);
  pr_info("[iob_eth] Sysfs - Write eth_hash0_adr: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_eth_hash1_adr_store(struct device *dev,
                                         struct device_attribute *attr,
                                         const char *buf, size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_eth_mutex)) {
    pr_info("[iob_eth] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_eth_mutex);
    return ret;
  }
  iob_data_write_reg(iob_eth_data.regbase, value,
                     IOB_ETH_CSRS_ETH_HASH1_ADR_ADDR,
                     IOB_ETH_CSRS_ETH_HASH1_ADR_W);
  mutex_unlock(&iob_eth_mutex);
  pr_info("[iob_eth] Sysfs - Write eth_hash1_adr: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_eth_txctrl_store(struct device *dev,
                                      struct device_attribute *attr,
                                      const char *buf, size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_eth_mutex)) {
    pr_info("[iob_eth] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_eth_mutex);
    return ret;
  }
  iob_data_write_reg(iob_eth_data.regbase, value, IOB_ETH_CSRS_ETH_TXCTRL_ADDR,
                     IOB_ETH_CSRS_ETH_TXCTRL_W);
  mutex_unlock(&iob_eth_mutex);
  pr_info("[iob_eth] Sysfs - Write eth_txctrl: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_tx_bd_cnt_show(struct device *dev,
                                    struct device_attribute *attr, char *buf) {
  u32 value =
      iob_data_read_reg(iob_eth_data.regbase, IOB_ETH_CSRS_TX_BD_CNT_ADDR,
                        IOB_ETH_CSRS_TX_BD_CNT_W);
  pr_info("[iob_eth] Sysfs - Read tx_bd_cnt: 0x%x\n", value);
  return sprintf(buf, "%u", value);
}

static ssize_t sysfs_rx_bd_cnt_show(struct device *dev,
                                    struct device_attribute *attr, char *buf) {
  u32 value =
      iob_data_read_reg(iob_eth_data.regbase, IOB_ETH_CSRS_RX_BD_CNT_ADDR,
                        IOB_ETH_CSRS_RX_BD_CNT_W);
  pr_info("[iob_eth] Sysfs - Read rx_bd_cnt: 0x%x\n", value);
  return sprintf(buf, "%u", value);
}

static ssize_t sysfs_tx_word_cnt_show(struct device *dev,
                                      struct device_attribute *attr,
                                      char *buf) {
  u32 value =
      iob_data_read_reg(iob_eth_data.regbase, IOB_ETH_CSRS_TX_WORD_CNT_ADDR,
                        IOB_ETH_CSRS_TX_WORD_CNT_W);
  pr_info("[iob_eth] Sysfs - Read tx_word_cnt: 0x%x\n", value);
  return sprintf(buf, "%u", value);
}

static ssize_t sysfs_rx_word_cnt_show(struct device *dev,
                                      struct device_attribute *attr,
                                      char *buf) {
  u32 value =
      iob_data_read_reg(iob_eth_data.regbase, IOB_ETH_CSRS_RX_WORD_CNT_ADDR,
                        IOB_ETH_CSRS_RX_WORD_CNT_W);
  pr_info("[iob_eth] Sysfs - Read rx_word_cnt: 0x%x\n", value);
  return sprintf(buf, "%u", value);
}

static ssize_t sysfs_rx_nbytes_show(struct device *dev,
                                    struct device_attribute *attr, char *buf) {
  u32 value =
      iob_data_read_reg(iob_eth_data.regbase, IOB_ETH_CSRS_RX_NBYTES_ADDR,
                        IOB_ETH_CSRS_RX_NBYTES_W);
  pr_info("[iob_eth] Sysfs - Read rx_nbytes: 0x%x\n", value);
  return sprintf(buf, "%u", value);
}

static ssize_t sysfs_frame_word_store(struct device *dev,
                                      struct device_attribute *attr,
                                      const char *buf, size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_eth_mutex)) {
    pr_info("[iob_eth] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_eth_mutex);
    return ret;
  }
  iob_data_write_reg(iob_eth_data.regbase, value, IOB_ETH_CSRS_FRAME_WORD_ADDR,
                     IOB_ETH_CSRS_FRAME_WORD_W);
  mutex_unlock(&iob_eth_mutex);
  pr_info("[iob_eth] Sysfs - Write frame_word: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_phy_rst_val_show(struct device *dev,
                                      struct device_attribute *attr,
                                      char *buf) {
  u32 value =
      iob_data_read_reg(iob_eth_data.regbase, IOB_ETH_CSRS_PHY_RST_VAL_ADDR,
                        IOB_ETH_CSRS_PHY_RST_VAL_W);
  pr_info("[iob_eth] Sysfs - Read phy_rst_val: 0x%x\n", value);
  return sprintf(buf, "%u", value);
}

static ssize_t sysfs_version_show(struct device *dev,
                                  struct device_attribute *attr, char *buf) {
  u32 value = iob_data_read_reg(iob_eth_data.regbase, IOB_ETH_CSRS_VERSION_ADDR,
                                IOB_ETH_CSRS_VERSION_W);
  pr_info("[iob_eth] Sysfs - Read version: 0x%x\n", value);
  return sprintf(buf, "%u", value);
}

// Device attributes
DEVICE_ATTR(moder, 0600, sysfs_moder_show, sysfs_moder_store);
DEVICE_ATTR(int_source, 0600, sysfs_int_source_show, sysfs_int_source_store);
DEVICE_ATTR(int_mask, 0600, sysfs_int_mask_show, sysfs_int_mask_store);
DEVICE_ATTR(ipgt, 0600, sysfs_ipgt_show, sysfs_ipgt_store);
DEVICE_ATTR(ipgr1, 0600, sysfs_ipgr1_show, sysfs_ipgr1_store);
DEVICE_ATTR(ipgr2, 0600, sysfs_ipgr2_show, sysfs_ipgr2_store);
DEVICE_ATTR(packetlen, 0600, sysfs_packetlen_show, sysfs_packetlen_store);
DEVICE_ATTR(collconf, 0600, sysfs_collconf_show, sysfs_collconf_store);
DEVICE_ATTR(tx_bd_num, 0600, sysfs_tx_bd_num_show, sysfs_tx_bd_num_store);
DEVICE_ATTR(ctrlmoder, 0600, sysfs_ctrlmoder_show, sysfs_ctrlmoder_store);
DEVICE_ATTR(miimoder, 0600, sysfs_miimoder_show, sysfs_miimoder_store);
DEVICE_ATTR(miicommand, 0600, sysfs_miicommand_show, sysfs_miicommand_store);
DEVICE_ATTR(miiaddress, 0600, sysfs_miiaddress_show, sysfs_miiaddress_store);
DEVICE_ATTR(miitx_data, 0600, sysfs_miitx_data_show, sysfs_miitx_data_store);
DEVICE_ATTR(miirx_data, 0600, sysfs_miirx_data_show, sysfs_miirx_data_store);
DEVICE_ATTR(miistatus, 0600, sysfs_miistatus_show, sysfs_miistatus_store);
DEVICE_ATTR(mac_addr0, 0600, sysfs_mac_addr0_show, sysfs_mac_addr0_store);
DEVICE_ATTR(mac_addr1, 0600, sysfs_mac_addr1_show, sysfs_mac_addr1_store);
DEVICE_ATTR(eth_hash0_adr, 0600, sysfs_eth_hash0_adr_show,
            sysfs_eth_hash0_adr_store);
DEVICE_ATTR(eth_hash1_adr, 0600, sysfs_eth_hash1_adr_show,
            sysfs_eth_hash1_adr_store);
DEVICE_ATTR(eth_txctrl, 0600, sysfs_eth_txctrl_show, sysfs_eth_txctrl_store);
DEVICE_ATTR(tx_bd_cnt, 0400, sysfs_tx_bd_cnt_show, sysfs_enosys_store);
DEVICE_ATTR(rx_bd_cnt, 0400, sysfs_rx_bd_cnt_show, sysfs_enosys_store);
DEVICE_ATTR(tx_word_cnt, 0400, sysfs_tx_word_cnt_show, sysfs_enosys_store);
DEVICE_ATTR(rx_word_cnt, 0400, sysfs_rx_word_cnt_show, sysfs_enosys_store);
DEVICE_ATTR(rx_nbytes, 0400, sysfs_rx_nbytes_show, sysfs_enosys_store);
DEVICE_ATTR(frame_word, 0600, sysfs_frame_word_show, sysfs_frame_word_store);
DEVICE_ATTR(phy_rst_val, 0400, sysfs_phy_rst_val_show, sysfs_enosys_store);
DEVICE_ATTR(version, 0400, sysfs_version_show, sysfs_enosys_store);

// Probe / Remove functions
static int iob_eth_create_device_attr_files(struct device *device) {
  int ret = 0;
  ret |= device_create_file(device, &dev_attr_moder);
  ret |= device_create_file(device, &dev_attr_int_source);
  ret |= device_create_file(device, &dev_attr_int_mask);
  ret |= device_create_file(device, &dev_attr_ipgt);
  ret |= device_create_file(device, &dev_attr_ipgr1);
  ret |= device_create_file(device, &dev_attr_ipgr2);
  ret |= device_create_file(device, &dev_attr_packetlen);
  ret |= device_create_file(device, &dev_attr_collconf);
  ret |= device_create_file(device, &dev_attr_tx_bd_num);
  ret |= device_create_file(device, &dev_attr_ctrlmoder);
  ret |= device_create_file(device, &dev_attr_miimoder);
  ret |= device_create_file(device, &dev_attr_miicommand);
  ret |= device_create_file(device, &dev_attr_miiaddress);
  ret |= device_create_file(device, &dev_attr_miitx_data);
  ret |= device_create_file(device, &dev_attr_miirx_data);
  ret |= device_create_file(device, &dev_attr_miistatus);
  ret |= device_create_file(device, &dev_attr_mac_addr0);
  ret |= device_create_file(device, &dev_attr_mac_addr1);
  ret |= device_create_file(device, &dev_attr_eth_hash0_adr);
  ret |= device_create_file(device, &dev_attr_eth_hash1_adr);
  ret |= device_create_file(device, &dev_attr_eth_txctrl);
  ret |= device_create_file(device, &dev_attr_tx_bd_cnt);
  ret |= device_create_file(device, &dev_attr_rx_bd_cnt);
  ret |= device_create_file(device, &dev_attr_tx_word_cnt);
  ret |= device_create_file(device, &dev_attr_rx_word_cnt);
  ret |= device_create_file(device, &dev_attr_rx_nbytes);
  ret |= device_create_file(device, &dev_attr_frame_word);
  ret |= device_create_file(device, &dev_attr_phy_rst_val);
  ret |= device_create_file(device, &dev_attr_version);
  return ret;
}

static void iob_eth_remove_device_attr_files(struct iob_data *iob_eth_data) {
  device_remove_file(iob_eth_data->device, &dev_attr_moder);
  device_remove_file(iob_eth_data->device, &dev_attr_int_source);
  device_remove_file(iob_eth_data->device, &dev_attr_int_mask);
  device_remove_file(iob_eth_data->device, &dev_attr_ipgt);
  device_remove_file(iob_eth_data->device, &dev_attr_ipgr1);
  device_remove_file(iob_eth_data->device, &dev_attr_ipgr2);
  device_remove_file(iob_eth_data->device, &dev_attr_packetlen);
  device_remove_file(iob_eth_data->device, &dev_attr_collconf);
  device_remove_file(iob_eth_data->device, &dev_attr_tx_bd_num);
  device_remove_file(iob_eth_data->device, &dev_attr_ctrlmoder);
  device_remove_file(iob_eth_data->device, &dev_attr_miimoder);
  device_remove_file(iob_eth_data->device, &dev_attr_miicommand);
  device_remove_file(iob_eth_data->device, &dev_attr_miiaddress);
  device_remove_file(iob_eth_data->device, &dev_attr_miitx_data);
  device_remove_file(iob_eth_data->device, &dev_attr_miirx_data);
  device_remove_file(iob_eth_data->device, &dev_attr_miistatus);
  device_remove_file(iob_eth_data->device, &dev_attr_mac_addr0);
  device_remove_file(iob_eth_data->device, &dev_attr_mac_addr1);
  device_remove_file(iob_eth_data->device, &dev_attr_eth_hash0_adr);
  device_remove_file(iob_eth_data->device, &dev_attr_eth_hash1_adr);
  device_remove_file(iob_eth_data->device, &dev_attr_eth_txctrl);
  device_remove_file(iob_eth_data->device, &dev_attr_tx_bd_cnt);
  device_remove_file(iob_eth_data->device, &dev_attr_rx_bd_cnt);
  device_remove_file(iob_eth_data->device, &dev_attr_tx_word_cnt);
  device_remove_file(iob_eth_data->device, &dev_attr_rx_word_cnt);
  device_remove_file(iob_eth_data->device, &dev_attr_rx_nbytes);
  device_remove_file(iob_eth_data->device, &dev_attr_frame_word);
  device_remove_file(iob_eth_data->device, &dev_attr_phy_rst_val);
  device_remove_file(iob_eth_data->device, &dev_attr_version);
  device_destroy(iob_eth_data->class, iob_eth_data->devnum);
  return;
}

#endif // H_IOB_ETH_SYSFS_H
